---
- name: inspec exec
  delegate_to: localhost
  changed_when: false
  command: >
    inspec exec {{ inspec_profile_dir }} --reporter json-min
      -b winrm
      --host {{ inventory_hostname }}
      --user {{ ansible_user_id }}
      --password {{ ansible_password }}
      {{ inspec_attr_arg }}
  no_log: true
  ignore_errors: yes
  register: inspec_out
  when: ansible_connection != "local"

- name: inspec exec locally
  changed_when: false
  command: inspec exec {{ inspec_profile_dir }} --reporter json-min {{ inspec_attr_arg }}
  no_log: true
  ignore_errors: yes
  register: inspec_out
  when: ansible_connection != "local"

- name: inspec exec - stdout
  debug:
    var: inspec_out.stdout | from_json
  when: inspec_out.rc == 0 or inspec_out.rc == 101

- name: inspec exec debug - stderr
  debug:
    var: inspec_out.stdout | from_json
  when: inspec_out.rc != 0 and inspec_out.rc != 101
  failed_when: true
